### ISSUE TITLE
Tabris init fails

### ISSUE THREAD

**Issue by Joshua-Beatty** [eclipsesource/tabris-js-cli#79] opened 2020-04-21 18:42 UTC
I've just installed tabris and am trying to set up a new project using `tabris init` but the process fails after the additional options section with this error:

`(node:15300) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\generator-tabris-js\app\templates-3.x\_package.json
    at EditionInterface.exports.copy (C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at module.exports.writing (C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\generator-tabris-js\app\generator.js:87:13)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\run-async\index.js:47:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\node_modules\yeoman-generator\lib\index.js:425:13)
    at processImmediate (internal/timers.js:443:21)
(node:15300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by cookieguru** [comment] 2020-04-21 18:53
Looks like not all the dependencies were installed correctly.  I see that globals are being stored in your Program Files directory so a normal user might not have write access to that.  From an Administrator command prompt or PowerShell try:
```batch
npm uninstall -g tabris-cli
npm install -g tabris-cli
```
and try again

**Comment by Joshua-Beatty** [comment] 2020-04-21 19:04
I reinstalled in an administrator command prompt and got the exact same error output when running `tabris init`

If its any help i got these warning upon installing the cli
``npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
C:\Program Files (x86)\Nodist\bin\tabris -> C:\Program Files (x86)\Nodist\bin\node_modules\tabris-cli\src\tabris.js
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Program Files (x86)\Nodist\v-x64\11.13.0\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.``

**Comment by cookieguru** [comment] 2020-04-21 19:40
I just tried with Node v10.20.1 x64 on Windows 10 and cannot reproduce it.

Which versions are you using?
`C:\Program Files (x86)\Nodist\bin\node.exe --version`
`C:\Program Files (x86)\Nodist\v-x64\11.13.0\node.exe --version`

I wonder if the different paths are causing problems; did by chance install the x86 version?  It looks like you have both x86 and x64 installed; the advice about using the node path might help it find it.  Or if you don't need the x86 version, uninstall Node and reinstall only the x64

**Comment by Joshua-Beatty** [comment] 2020-04-21 20:20
So it seems the problem was with nodist. 
A clean nodist isntall will install to both `C:\Program Files (x86)\Nodist\bin\`  and to `C:\Program Files (x86)\Nodist\v-x64\11.13.0\`
I uninstalled nodist and reinstalled using the installer from [nodejs.org](https://www.nodejs.org) and `tabris init` works as intended

**Comment by mpost** [comment] 2020-04-22 07:01
Great to hear. Closing as resolved.

**Closed as completed by mpost** 2020-04-22 07:01 UTC
